### ISSUE TITLE
Rename of geofence is not working

### ISSUE THREAD

**Issue by andi2022** [versx/ChuckDeviceController#30]
When i try to rename an existing geofence there is an error.
`Error! Geofence with name 'test2' does not exist`
The same error is also when i try to rename an instance.

![image](https://user-images.githubusercontent.com/46579547/110698027-6c59f880-81ed-11eb-8088-575db9c41341.png)
![image](https://user-images.githubusercontent.com/46579547/110698035-6d8b2580-81ed-11eb-96aa-2fb7fc1dca97.png)

**Comment by versx** [comment]
Thanks, I need to fix this, renaming anything won't work at the moment.
