### ISSUE TITLE
Catch rate is not processed

### ISSUE THREAD

**Issue by andi2022** [versx/ChuckDeviceController#33]
I don't know if it is a part of the re-implement from the pvp stats but the catch rate is not processing.
![image](https://user-images.githubusercontent.com/46579547/110707681-ed1ef180-81f9-11eb-8101-40ea0f3187af.png)

**Comment by versx** [comment]
I think it might be an issue with protos tbh, I also noticed I wasn't getting any capture rates saved. @Furtif

**Comment by Mygod** [comment]
Catch rate is per-account and should not be saved imo.

**Comment by versx** [comment]
> Catch rate is per-account and should not be saved imo.

🤔 Need more confirmations of this, AFAIK if it's scanned with an account level >= 30 the catch rate is for everyone. Otherwise it's treated like IV stats with account level < 30.

**Comment by Mygod** [comment]
Bro. It depends on your medal level. Give me your catch rates and I will reverse engineer your account's medal using this: https://gamepress.gg/pokemongo/catchcalc#/

**Comment by versx** [comment]
Ah you're right, my bad.

**Comment by Mygod** [comment]
Fun fact: Chuck doesn't save catch rates.
