### ISSUE TITLE
Add accounts is not working

### ISSUE THREAD

**Issue by bschultz** [versx/ChuckDeviceController#41]
Accounts are not saved to database but I also didn't get any errors in log

**Comment by versx** [comment]
I can't replicate this 🤔 it adds the account to the database for me.

![image](https://user-images.githubusercontent.com/1327440/111715618-75f8e700-8811-11eb-90c9-3c6ee2a35f3a.png)

![image](https://user-images.githubusercontent.com/1327440/111715641-801ae580-8811-11eb-8994-230f4e0da3cc.png)

**Comment by clburlison** [comment]
Also unable to replicate. This is working over here on latest commit with mariadb 10.5.

**Comment by bschultz** [comment]
Oh, forgot to mention that I wanted to add with custom level (like in the example).
Try/test with: `test,tester,23`
This is not working. Without the level in the list it works here too

**Comment by versx** [comment]
Had a feeling 😅, I'll push a fix in a bit.

**Comment by versx** [comment]
Should be fixed in https://github.com/versx/ChuckDeviceController/commit/0b2442132b5ee7c3a13633b9c4649bbb292ce3d9
