### ISSUE TITLE
Change instance level defaults

### ISSUE THREAD

**Issue by clburlison** [versx/ChuckDeviceController#46]
**Is your feature request related to a problem? Please describe.**
This is a quality of life enhancement. 

**Describe the solution you'd like**
Change the default Min level & Max level for all instance types from: 0-30 to 30-40.

**Describe alternatives you've considered**
We can keep the system as it is. This will require more clicking during setup but isn't the end of the world as it happens at initial setup time and not super often after the project is up.

**Additional context**
Most of have been mapping for a long time and have a large stock of lvl 30 accounts. Many scanning features require the higher level accounts. Realistically people should only be using accounts under level 30 for questing or leveling up purposes.

(feel free to close if not interested in the change)

**Comment by versx** [comment]
Changed in latest.
